FROM nvcr.io/nvidia/cuda:11.8.0-cudnn8-devel-ubuntu22.04 as cuda11
WORKDIR /
COPY . /
RUN apt-get update
RUN apt-get install -y build-essential libxmu-dev libxi-dev libgl-dev libosmesa-dev git liblog4cplus-dev cmake curl
RUN mkdir build && cd build && cmake .. && make && make install

#FROM nvcr.io/nvidia/cuda:10.2-devel-ubuntu18.04 as cuda10
#WORKDIR /
#COPY . /
#RUN apt-get install -y build-essential libxmu-dev libxi-dev libgl-dev libosmesa-dev git liblog4cplus-dev curl wget build-essential libssl-dev
#RUN wget https://github.com/Kitware/CMake/releases/download/v3.20.0/cmake-3.20.0.tar.gz && tar -zxvf cmake-3.20.0.tar.gz && cd cmake-3.20.0 && ./bootstrap && ./bootstrap && make && make install
#RUN mkdir build && cd build && cmake .. && make && make install


FROM nvcr.io/nvidia/cuda:11.8.0-cudnn8-runtime-ubuntu22.04
WORKDIR /
COPY --from=cuda11 /root/GVirtuS /GVirtuS
RUN sed -i 's/127.0.0.1/0.0.0.0/g' /GVirtuS/etc/properties.json
ENV GVIRTUS_HOME=/GVirtuS
ENV LD_LIBRARY_PATH=${GVIRTUS_HOME}/lib:${LD_LIBRARY_PATH}
CMD ["/GVirtuS/bin/gvirtus-backend", "/GVirtuS/etc/properties.json"]