FROM nvcr.io/nvidia/cuda:12.0.0-cudnn8-devel-ubuntu22.04 as cuda11
WORKDIR /
RUN apt-get update
RUN apt-get install -y git  cmake curl

RUN git clone -b v12.0 https://github.com/NVIDIA/cuda-samples
RUN cd cuda-samples && make EXTRA_NVCCFLAGS="--cudart=shared" all

FROM ghcr.io/megacloudcontainer/gvirtus/client:dev
WORKDIR /
COPY --from=cuda11 /cuda-samples/bin/x86_64/linux/release/ /usr/local/bin/
COPY --from=cuda11 /cuda-samples /cuda-samples
ENV GVIRTUS_HOME=/GVirtuS
ENV GVIRTUS_CONFIG=${GVIRTUS_HOME}/etc/properties.json
ENV LD_LIBRARY_PATH=${GVIRTUS_HOME}/lib:${GVIRTUS_HOME}/lib/frontend:${LD_LIBRARY_PATH}
ENV GVIRTUS_LOGLEVEL=10000
#RUN ln -s /GVirtuS/lib/frontend/libcudart.so.12  /GVirtuS/lib/frontend/libcudart.so.12.0
CMD ["sleep", "infinity"]