FROM nvcr.io/nvidia/cuda:12.0.0-cudnn8-devel-ubuntu22.04 as cuda12
WORKDIR /
COPY . /
RUN apt-get update
RUN apt-get install -y build-essential libxmu-dev libxi-dev libgl-dev libosmesa-dev git liblog4cplus-dev cmake curl wget
RUN wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64/cuda-archive-keyring.gpg && \
    mv cuda-archive-keyring.gpg /usr/share/keyrings/cuda-archive-keyring.gpg && \
    echo "deb [signed-by=/usr/share/keyrings/cuda-archive-keyring.gpg] https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64/ /" | tee /etc/apt/sources.list.d/cuda-ubuntu2204-x86_64.list && \
    wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64/cuda-ubuntu2204.pin && \
    mv cuda-ubuntu2204.pin /etc/apt/preferences.d/cuda-repository-pin-600

RUN apt-get update && apt-get install -y cuda

ENV PATH="/usr/local/cuda/bin:${PATH}"
ENV LIBRARY_PATH="/usr/local/cuda/targets/x86_64-linux/lib/stubs:$(LIBRARY_PATH}"
ENV LD_LIBRARY_PATH="/usr/local/cuda/lib64:/usr/local/cuda/targets/x86_64-linux/lib/stubs:${LD_LIBRARY_PATH}"
RUN mkdir build && cd build && cmake .. && make && make install

#FROM nvcr.io/nvidia/cuda:11.8.0-cudnn8-devel-ubuntu22.04 as cuda11
#WORKDIR /
#COPY . /
#RUN apt-get update
#RUN apt-get install -y build-essential libxmu-dev libxi-dev libgl-dev libosmesa-dev git liblog4cplus-dev cmake curl
#RUN mkdir build && cd build && cmake .. && make && make install

#FROM nvcr.io/nvidia/cuda:10.2-devel-ubuntu18.04 as cuda10
#WORKDIR /
#COPY . /
#RUN apt-get install -y build-essential libxmu-dev libxi-dev libgl-dev libosmesa-dev git liblog4cplus-dev curl wget build-essential libssl-dev
#RUN wget https://github.com/Kitware/CMake/releases/download/v3.20.0/cmake-3.20.0.tar.gz && tar -zxvf cmake-3.20.0.tar.gz && cd cmake-3.20.0 && ./bootstrap && ./bootstrap && make && make install
#RUN mkdir build && cd build && cmake .. && make && make install


FROM nvcr.io/nvidia/cuda:12.0.0-cudnn8-runtime-ubuntu22.04
WORKDIR /
COPY --from=cuda12 /root/GVirtuS /GVirtuS
RUN sed -i 's/127.0.0.1/0.0.0.0/g' /GVirtuS/etc/properties.json
ENV GVIRTUS_HOME=/GVirtuS
ENV LD_LIBRARY_PATH=${GVIRTUS_HOME}/lib:${LD_LIBRARY_PATH}
ENV GVIRTUS_LOGLEVEL=10000
RUN mkdir /licenses && mv /NGC-DL-CONTAINER-LICENSE /licenses/NGC-DL-CONTAINER-LICENSE
CMD ["/GVirtuS/bin/gvirtus-backend", "/GVirtuS/etc/properties.json"]